### ISSUE TITLE
show closed and reopen markers inline with comments

### ISSUE THREAD

**Issue by cebe** [github/android#123]
just as it is on Github.

**Comment by EzraBrooks** [comment]
Is this still an issue in the current build? If so, can you show some screenshots to demonstrate the issue?

**Comment by cebe** [comment]
Just like above this commit you see that I have closed and opened the issue.
This is not displayed in the android client.

**Comment by Meisolsson** [comment]
I'm currently working on this, should have a PR ready by tomorrow

**Comment by cebe** [comment]
nice :)

**Comment by Meisolsson** [comment]
![screenshot_2015-02-07-19-09-05](https://cloud.githubusercontent.com/assets/3757908/6093600/236bfe36-af06-11e4-9815-42995a06c711.png) Something like this?

**Comment by cebe** [comment]
exactly. looks really nice :)

**Comment by cebe** [comment]
Maybe the icons should be red for close and green for reopen, not sure what the styleguide is here.

**Comment by Meisolsson** [comment]
This is with color (there is a purple one for merged)
![screenshot_2015-02-07-22-56-09](https://cloud.githubusercontent.com/assets/3757908/6094115/ae6a9540-af1c-11e4-9161-c136f69af787.png)

**Comment by cebe** [comment]
looks much better
