### ISSUE TITLE
Support Pull-to-Refresh on the News sections

### ISSUE THREAD

**Issue by VladRassokhin** [github/android#130]
It's really useful to check news updates with pull-to-refresh.

Relates to #97

**Comment by VladRassokhin** [comment]
So why it's closed now again?

**Comment by fadils** [comment]
It's fixed and already in the master.

**Comment by VladRassokhin** [comment]
Nice! Thanks! Quite good reason to close issue :)

**Comment by fadils** [comment]
:)
