### ISSUE TITLE
Force close on login

### ISSUE THREAD

**Issue by xpansive** [github/android#131]
When I log in to the app on a fresh install, it says it can't connect to github. After 10 seconds or so it force closes and then proceeds to do so again every time I open the app. There is a copy of the logcat output [here](https://gist.github.com/3145500), it seems to be saying that the class org.eclipse.egit.github.core.User cannot be found. My phone is a iNQ Cloud Touch (absolutely horrible phone, don't buy it) and it runs Android 2.2.

Any idea what could be causing this and how it could possibly be fixed?

**Comment by EzraBrooks** [comment]
Unless you can replicate this on a newer Android version and the newest development version of the app, I would assume this problem has been fixed.
