### ISSUE TITLE
can't star in old Android Device

### ISSUE THREAD

**Issue by TETRA2000** [github/android#369]
I pressed the star button in the repo menu, I got a "Starring failed" toast message.
It occered in an Android 2.2 AVD and my Android 2.2 phone.
It didn't occer in new Android(4.1) AVD and devices.

Logcat
05-26 13:02:13.046: D/StarRepositoryTask(278): Exception starring repository
05-26 13:02:13.046: D/StarRepositoryTask(278): java.io.IOException: Length Required (411)
05-26 13:02:13.046: D/StarRepositoryTask(278): 	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:564)
05-26 13:02:13.046: D/StarRepositoryTask(278): 	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
05-26 13:02:13.046: D/StarRepositoryTask(278): 	at org.eclipse.egit.github.core.client.GitHubClient.put(GitHubClient.java:773)
05-26 13:02:13.046: D/StarRepositoryTask(278): 	at org.eclipse.egit.github.core.client.GitHubClient.put(GitHubClient.java:584)
05-26 13:02:13.046: D/StarRepositoryTask(278): 	at org.eclipse.egit.github.core.service.WatcherService.watch(WatcherService.java:296)
...

**Comment by EzraBrooks** [comment]
This bug is occurring on an SDK level that is now out of project scope. As @TETRA2000 indicated it doesn't occur on newer SDK levels, I think this issue should be closed.

**Comment by TETRA2000** [comment]
@EzraBrooks thanks for comment. Closed this issue.
