### ISSUE TITLE
About build

### ISSUE THREAD

**Issue by yang-le** [github/android#421]
The maven version should be 3.0.5, and the android sdk API level should be 16.
I try build it with Maven 3.1.1, but failed.

**Comment by Meisolsson** [comment]
Is this still relevant as we have mostly moved to Gradle?

**Comment by EzraBrooks** [comment]
What are the remaining reasons we haven't switched entirely to Gradle?

**Comment by fadils** [comment]
Closed as Gradle is preferred now.
