### ISSUE TITLE
Update CodeMirror to the latest version

### ISSUE THREAD

**Issue by XhmikosR** [github/android#423]
http://codemirror.net/doc/releases.html

**Comment by XhmikosR** [comment]
Was this done?

**Comment by jonan** [comment]
It was updated to v4.8.0 released on Nov 22, 2014.
There have been new releases since then, so we might need to update again soon, but this issue is about updating to the last 2.x or the first 3.x so it should be closed.

**Comment by XhmikosR** [comment]
OK, cool.
