### ISSUE TITLE
Multiple dex files or ClassNotFound errors while building

### ISSUE THREAD

**Issue by raghavsethi** [github/android#447]
Error while building: 'Multiple dex files define Lorg/eclipse/egit/github/core/Application'

Tried unchecking all permutations of Android 4.1, Android Private Libraries and Android dependencies from the Order and Export section in Project Properties for the project and the library projects it depends on. I am able to get it to build when I uncheck the Android Private Libraries item in my main project, but then I get a ClassNotFound error while starting the main activity.

Only the main project requires org.eclipse.egit.github.core-2.1.2.jar file, so I don't see how I could get a conflict there. The only other common dependency is android-supportv4, but I fixed the Order and Export section appropriately for that, and the error message does not mention it anyway.

**Comment by EzraBrooks** [comment]
This error is occurring when importing to Eclipse, not Android Studio. Am I right in believing we are specifically supporting Android Studio w/ Gradle now, @fadils?

**Comment by fadils** [comment]
Please use Android Studio.
