### ISSUE TITLE
Switch from ABS to AppCompat

### ISSUE THREAD

**Issue by hzsweers** [github/android#658]
This would be a major first step to implementing Material Design.

Note that there are two bugs currently in AppCompat that we'd need to work around:
* Tint manager reusing icon colors for all instances (including across the backstack). Not an issue if we use the same theme for all toolbars/actionbars, but good to keep in mind. It's fixed internally, but after "releasing" it, then apparently forgetting to, it's now in limbo and being held back until the next "major" release (whenever that is).
  * [Issue tracker](https://code.google.com/p/android/issues/detail?id=78289&can=1&q=appcompat%20overflow&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars)
* Appcompat toolbars/actionbars crash on Samsung devices running 4.2.2 due to a Samsung ROM bug. This can be avoided though via proguard, so not terribly concerning.
  * [Issue tracker](https://code.google.com/p/android/issues/detail?id=78377)

This issue doesn't need to be resolved by implementing everything appcompat has to offer. This is just about weening the app off of ActionBarSherlock (which has been deprecated for some time now) and switching to AppCompat. Other material design features can be worked on separately after this is ready.

I plan to start working on this this week in my [fork](https://github.com/hzsweers/android), anyone should feel free to chime in. Once it's ready, I'll pull request.

**Comment by hzsweers** [comment]
This would also require raising minSDK version to 9. Would you guys be open to that @fadils? Froyo (v. 8) only accounts for [0.5%](https://developer.android.com/about/dashboards/index.html) of devices now. It would be preferable to actually raise it all the way to 15, which would make development much easier and still support 90% of devices. I can't see your play store stats, but given the developer nature of the app, I would hazard a guess that 15 would actually cover much more than 90% of your users :)

**Comment by Meisolsson** [comment]
I tried doing this and ended up needing to update RoboGuice to v.3 which introduced a bug which makes the app unable to load some things. (v.3 introduces RoboActionbarActicity)

**Comment by hzsweers** [comment]
Switching to appcompat or bumping the min SDK version?

**Comment by Meisolsson** [comment]
Appcompat

**Comment by hzsweers** [comment]
Interesting, guess I'll find out :)

**Comment by hzsweers** [comment]
Was able to do it without updating RoboGuice, but would be nice to use v3's first-party `RoboActionBarActivity`. Going to keep it at v2 for now, and leave updating to v3 as a separate job since it could be a pretty big change.

**Comment by hzsweers** [comment]
Also, appcompat actually required v11 for some of thing. At that point, should really just set the minSDKversion to 15 (there's maybe 0.1% of users between 11 and 15).

**Comment by Meisolsson** [comment]
There is a pull request for the bug I was having in v.3, but it will take a while for them to release

**Comment by hzsweers** [comment]
Could you link it? I'm curious to see what it is

**Comment by Meisolsson** [comment]
https://github.com/roboguice/roboguice/issues/266 This is the issue, it has a PR

**Comment by fadils** [comment]
Personally, I would love to bump our minSDK to 15. 
I'm just saying.

**Comment by jonanp** [comment]
I would also like to update the minSDK to 15, but I don't know the number of devices out there that use the app with older SDKs.

**Comment by hzsweers** [comment]
Can you guys check your play store developer console? Just android alone
puts a little over 90% of devices being covered by API 15. I'm willing to
bet GitHub's user base is much closer to the right of that bell curve, and
closer to 100%

**Comment by fadils** [comment]
Let's go for it, I would say.

**Comment by hzsweers** [comment]
:balloon:

**Comment by fadils** [comment]
Close via #661
