### ISSUE TITLE
Restructure project hierarchy to be a proper gradle project

### ISSUE THREAD

**Issue by hzsweers** [github/android#659]
Right now it's still set up like an eclipse project, just with hook-ins to support gradle. I will try to do this today and PR back in tonight. I'm suggesting this on the assumption that you guys have switched over to Android Studio now that it's stable, so please let me know if this isn't viable right now :smiley:

**Comment by jonanp** [comment]
We still keep the old structure because we didn't want to remove maven support just yet, but I'm not very confident maven is still working.

I think somethings are still missing for Gragle (e.g. runing tests from Travis) and maven should be there until we fix it.

**Comment by hzsweers** [comment]
I see, we could open that as a separate issue and close this for now?
