### ISSUE TITLE
Materialize Tab UI

### ISSUE THREAD

**Issue by hzsweers** [github/android#662]
Current tab UI looks pretty dated. Using the [SlidingTabLayout](https://developer.android.com/samples/SlidingTabsBasic/src/com.example.android.common/view/SlidingTabLayout.html) sample included in the SDK, we can achieve a much more material-y look.

Note this is based on my AppCompat updates in #658 

![2015-01-05 02 25 04](https://cloud.githubusercontent.com/assets/1361086/5608743/1de275b4-9442-11e4-9a4a-29c5580c99ed.png)

**Comment by hzsweers** [comment]
Note to self or whoever tackles this:

To remove the actionbar shadow, should be as simple as adding this line to the theme

```xml
<item name="android:windowContentOverlay">@null</item>
```

**Comment by mustafa01ali** [comment]
@hzsweers If you have not started working on this, I can take this up.

**Comment by hzsweers** [comment]
Go for it!

**Comment by mustafa01ali** [comment]
Vjchccy

**Comment by mustafa01ali** [comment]
Cool, I'll submit a PR soon.
