### ISSUE TITLE
Switch from ActionBar Spinner to Navigation Drawer

### ISSUE THREAD

**Issue by hzsweers** [github/android#664]
As discussed in #661. The current spinner navigation isn't really intuitive, and switching to a navigation drawer would be a good step forward. ActionBar's list navigation is deprecated now, so a switch would need to happen sooner or later anyway. This would also make the navigation more readily able to accept new areas to navigate to (settings, profile, etc.)

There's a couple good mockups in #368, I'll try to mock up a more material version tonight.

**Comment by Meisolsson** [comment]
When i was playing around with my own version i made this 
![image](https://cloud.githubusercontent.com/assets/3757908/5646555/f1c49be0-967d-11e4-89ab-ba30ba82044d.png) 

It's made with the material design guidelines in mind(some things need tweaking)

**Comment by hzsweers** [comment]
Ooooo very nice. I feel like we could make the header a little more material by displaying some information about the account, and with a different color/background. Also the list header color generally uses the accent color in MD iirc.

I was working on one as well but didn't really get a chance to work more on it until tonight. How does this look? (Ignore the wrong icons/font, I'm not that familiar with mockup tools :stuck_out_tongue_winking_eye:)

![screenshot 2015-01-07 20 25 24](https://cloud.githubusercontent.com/assets/1361086/5657875/9c844e7c-96ab-11e4-9c39-9e3aca3c7c2b.png)

**Comment by Meisolsson** [comment]
Looks good, merging the two would look great! Last night I say down an made some ground work for the navigation drawer, mostly turning old activities intro fragments. So if I have the time i might PR tonight

**Comment by hzsweers** [comment]
Cool cool

**Comment by fadils** [comment]
Looks awesome!
Finally, this app is on the verge of a UI upgrade it so deserves. =)

One thing, I was thinking about making the header in the nav drawer to be more compact.

Perhaps like this:
![play-newstand-navdrawer](https://cloud.githubusercontent.com/assets/6204776/5658483/007c3686-9735-11e4-8f8e-91f3776d436f.png)

What do you guys think?

**Comment by hzsweers** [comment]
Yeah that would make sense since there's not really a user "cover photo" that we could show there or anything

**Comment by mustafa01ali** [comment]
+1 for compact header

**Comment by Meisolsson** [comment]
It looks like i might have to update the Octicons because the home icon was added later. This means that some of the icons will be changed since they are no longer there. But I will also mean that we will have the same icons as the website. Any objections?

**Comment by hzsweers** [comment]
@Meisolsson are you working on a mockup or actively developing this?

**Comment by Meisolsson** [comment]
Developing for the moment

**Comment by hzsweers** [comment]
ok good to know, please link your fork/branch.

It would be nice if GitHub could provide these icons. @fadils?

**Comment by Meisolsson** [comment]
Octicons is the GitHub icons made by GitHub

**Comment by hzsweers** [comment]
I know, I just mean it would be convenient if they gave us official icons at the right resolutions so we don't have to go hunting ourselves :smiley:

**Comment by Meisolsson** [comment]
Well yeah, but since it's a font it cab scale to the perfect size and it has the same icon as the website. So adding drawables would be worse

**Comment by hzsweers** [comment]
Are we talking about font or icons?

**Comment by Meisolsson** [comment]
It's an icon font (https://github.com/github/octicons)

**Comment by hzsweers** [comment]
Ah I see. Well, I'd wait for one of them to chime in then, I'm not familiar with this.

**Comment by Meisolsson** [comment]
No problems, just wanted to ask. I'll push to my fork later so you can see the progress

**Comment by fadils** [comment]
No problems with the icons so please proceed..

**Comment by Meisolsson** [comment]
@hzsweers The black background that you use in you mock would look great. Could you send a copy?

**Comment by Meisolsson** [comment]
So this is almost ready for a PR: http://imgur.com/uDSHpOv

Any ideas on what de should put under the username if the user doesn't have their email public?

**Comment by hzsweers** [comment]
@Meisolsson sorry for not responding earlier, it was 6am my time and I forgot to respond :stuck_out_tongue_winking_eye: 

Looks like you found the image, though I'd be open for another as well since I'm not sure GitHub even owns that image. It should be an official logo to avoid any copyright/licensing issues.

As for the username, they would be logged in at that point regardless right? I don't think they would need to worry about hiding/showing their username if they don't usually keep it public, as they've already logged in at this point.

**Comment by Meisolsson** [comment]
The image should be replaced for copyright etc. But one with equal colors would be nice.
The problem about the e-mail is that the API only gives you the public email. So if you have not set a public email nothing will come up.

**Comment by hzsweers** [comment]
Ah interesting. Seems like an odd shortcoming of the API though. Best thing to do there IMO is just vertically center the username

**Comment by Meisolsson** [comment]
Yeah had that thought too, will try it tomorrow.
