### ISSUE TITLE
Material Tab's Title Inconsistencies

### ISSUE THREAD

**Issue by fadils** [github/android#669]
When opening a personal profile, then the tab shows what should be in organization and vice versa.

Screenshots for reference:

- Organization's tab fills up the personal's page

![screenshot_2015-01-13-10-03-16](https://cloud.githubusercontent.com/assets/6204776/5715730/03525b80-9b11-11e4-9049-95443e005cca.png)

- Personal's tab fills up the organization's page (and of course, we cannot slide to "Following" tab)

![screenshot_2015-01-13-10-04-29](https://cloud.githubusercontent.com/assets/6204776/5715736/1de6e98e-9b11-11e4-9f70-133edb23ba44.png)

**Comment by fadils** [comment]
cc'ed: @mustafa01ali 

It seems to me you're missing setting up the right title for textview tab.
And the tab count, too.

Should create the equivalent `createTabs()` in previous `TabPagerActivity`

**Comment by Meisolsson** [comment]
We only have to call  <code> SlidingTabLayout.setViewPager(ViewPager) </code>, this updates the tabs according to the viewpager count from the adapter.

**Comment by fadils** [comment]
@Meisolsson I'm sorry it's been a rough day for me. Could you please submit a PR?
That would be appreciated.

**Comment by Meisolsson** [comment]
Fixed in #670
