### ISSUE TITLE
Update on navigation drawer's material design

### ISSUE THREAD

**Issue by fadils** [github/android#677]
As of this reference: http://www.google.com/design/spec/patterns/navigation-drawer.html

**Comment by keyeechen** [comment]
The reference is quite helpful,but if it`s tough to design the github app with material design completely.

**Comment by Meisolsson** [comment]
When I did the implementation I based it of this. So most of the colors and margins are correct. Don't know what's missing

**Comment by fadils** [comment]
@Meisolsson it was an awesome work. Not many things to add.

This issue is brought so that we can have a good discussion about the drawer. For example,

1. Changing accounts. Should we keep it as-is, which already awesome btw. Or we want to follow the link. And the latest gmail app also creates an animation for switching between accounts.
This is up for discussion.

2. Scroll or not to scroll. Up for discussion.

3. Settings and support activity. Then, we definitely need to add these.

That's why the title is "Update" to your already material-based nav drawer.

Keep up the good work.

**Comment by Meisolsson** [comment]
The account change is not really a change of account. The orgs has nothing to do with the other items (Gist, Bookmarks and Issue Dashboard) so for UX we should not change that.

**Comment by fadils** [comment]
I will close this and open a more specific one then. Thanks @Meisolsson
