### ISSUE TITLE
manual refresh

### ISSUE THREAD

**Issue by mananwason** [github/android#687]
When I open the app and the phone is not connected to the internet, it works fine but when just after that I connect it to the internet, I have to manually press the refresh button. It should refresh by itself.

**Comment by EzraBrooks** [comment]
Reliably implementing this would require adding the permission to read network status, I believe. I'm not sure it's worth adding a permission to the app (what with the current drama over app permissions) for this small feature. I don't personally think it's a feature that needs implemented.

@fadils, @hzsweers, what do you think?

**Comment by hzsweers** [comment]
I don't think this would be practical. I don't know of any major apps in the while that do this either.

**Comment by fadils** [comment]
Thanks for the input @hzsweers @EzraBrooks

**Comment by mananwason** [comment]
Yeah I also think if we have to add a new permission, then it's not worth it.
