### ISSUE TITLE
Question - Google play store app outdated. Will be updated?

### ISSUE THREAD

**Issue by fernandog** [github/android#689]
The only option I have is to compile the code in order to have the APK?
or an update will be release?
thanks.

**Comment by jonanp** [comment]
The app will be updated eventually (#682), but no date yet.

Current master is not stable enough for an official release, not even compared with the current version in the Play Store that has quite a few known bugs.

**Comment by fernandog** [comment]
@jonanp  thanks for the reply. what if I want to test and make some commits and open issues to help the devs? Isn't possible to release a dev apk in "releases" ?

**Comment by jonanp** [comment]
The only way you can test and contribute to the development version of the app is compiling it your self, we don't have development builds or anything like that.

**Comment by fernandog** [comment]
@jonanp  will try. thanks! closing issue
