### ISSUE TITLE
User avatar & file view

### ISSUE THREAD

**Issue by danielFerecatu** [github/android#693]
The user avatar size (in navigation drawer) should be 48dp for better visibility and username align to 72dp padding of list items
![1a](https://cloud.githubusercontent.com/assets/10303486/6044839/bbaa1260-ac9e-11e4-96be-f727c483df19.png)

and in file view toolbar, between avatar and text should be at least 4dp.
![2b](https://cloud.githubusercontent.com/assets/10303486/6044973/7c3bd612-ac9f-11e4-859c-a4cf1697de22.png)

If you agree with me i'll make a pull request.

**Comment by EzraBrooks** [comment]
I certainly agree with the padding between the avatar and text in the toolbar, but I'm not terribly impacted by the sizing of the user icon.

**Comment by fadils** [comment]
@danielFerecatu for navigation drawer please refer to http://www.google.com/design/spec/patterns/navigation-drawer.html

Whatever you find that's not aligned to MD spec, then your PR is welcome.

**Comment by danielFerecatu** [comment]
@fadils at first i wanted to implement the navigation drawer from material design but i've found that not all the dimensions were matching the 4dp grid so i thought to leave them as they were.

If this app is going to have a material design theme then i am glad to help implementing it. And one more thing, i looked for that file view toolbar and wasn't able to find it, maybe you can help me.

![screenshot_2015-02-05-13-47-53](https://cloud.githubusercontent.com/assets/10303486/6059733/b3596760-ad3d-11e4-850b-c54b2693afd7.png)

**Comment by hzsweers** [comment]
@danielFerecatu please take a look at #713, as it covers some of what you mention

Also, I don't think there's anything we can do about the toolbar icon/text spacing unless someone feels like implementing a subclass that does this. Icons in the actionbar are discouraged in material design, and they kind of kick you for doing it with this ugly UI

**Comment by fadils** [comment]
Closed via #713
