### ISSUE TITLE
Use of deprecated Android API functions

### ISSUE THREAD

**Issue by EzraBrooks** [github/android#705]
The project has a *lot* of deprecated functions lurking around in its older classes. I suggest that we, on the project as a whole, remove any instances of
```
@SupressWarnings("deprecation")
```
This would allow people working on the code to easier see deprecated method use and replace it while they are working in the class anyway. Since we are rebuilding much of the app for new API versions and Material Design anyway, we should modernise the code as well.

**Comment by iambmelt** [comment]
Agree - should not squelch.

**Comment by EzraBrooks** [comment]
If I had my way, I'd remove all warning suppression and all code that ignores exceptions instead of handling them. That's one of my pet peeves about Java and other high-level languages' development processes - too many people ignore problems instead of solving them.

**Comment by MRJpcHUT** [comment]
@ezrabrooks issue, yes I agree. Issues concerning warning suppression = issues unsolved. It should be a primary concern (considering material design) yet, backwards compatibility reasons a prevalent issue (can't use the app of you can't even use it) android 2.3-. Should be a standard of usability (yet,could be opinionated) somebody change my mind.

-good vibes, mrj
