### ISSUE TITLE
Consolidation

### ISSUE THREAD

**Issue by MRJpcHUT** [github/android#711]
i realize that I just joined Git two days ago... I feel this is the issue with this particular project(might just be my lack of experience !important) but it seems the issue is a lack of central direction (in terms of communication) and goals for this particular project.

I feel like there needs to be set goals, moreover milestones to this project. A sense of direction, and correct me if I'm wrong, an evaluation of what the original goals were and rethinking a system to achieve those goals.

I can contribute project management, UX, graphics and audio production to this project. Granted I need to get up to speed on the projectional objective as a whole, but I could help as director. 

Lmk what you guys think, but I feel I accelerate in objective satisfaction, and I'm asking all of you to take a risk on that.

-mrj

**Comment by fadils** [comment]
@MRJpcHUT you're welcome to contribute.

**Comment by MRJpcHUT** [comment]
Awesome. Where can I get more information for the scope?

**Comment by EzraBrooks** [comment]
The scope is mainly to provide the functionality that the web interface provides, if possible via the GitHub API.

**Comment by MRJpcHUT** [comment]
Ahh that makes sense. I'm brand new to GitHub, so I have a few questions. But I'll get started on a UI structure and best practice concept, depending on where you guys are at this point. Are you available for a chat via G+ or similar network?
