### ISSUE TITLE
GitHub Android App: Please make it possible to type and edit the actual repository file

### ISSUE THREAD

**Issue by dotcablogger** [github/android#715]
When in the Android app, please make it possible to type and edit the
actual repository file. I have tried with my HTC One phone and the app does
not allow me to type a new repository file nor edit within the file.

**Comment by jensz12** [comment]
+1

**Comment by XieQingShan** [comment]
Great~

**Comment by alorma** [comment]
Modify or create new file implies to make a new commit... not cool

**Comment by fadils** [comment]
Thanks @alorma. And doing it from a smartphone just makes it a bit harder to form clean code.
Sorry guys.

**Comment by KostasLifeboy** [comment]
But, what about tablets?
