### ISSUE TITLE
Support v7 conflict when use with actionbarsherlock

### ISSUE THREAD

**Issue by omiu** [github/android#740]
I really need to have support v7 library in project next to actionbarsherlock, but it seems they don't like to be there together. I really need the PopupMenu to use with api 10, and v7 has it, actionbarsherlock it doesnt. I m waiting for a solution.

Thx

**Comment by fadils** [comment]
As you said, they don't like to be there together.
You just have to migrate ABS to AppCompat.

After all, this isn't related to the app. You'd better ask in stackoverflow.
