### ISSUE TITLE
Can't see issues :(

### ISSUE THREAD

**Issue by rogama25** [github/android#742]
I'm using the last update of GitHub (1.9, android 4.2.2) and it shows the list of issues but you can't see the content of the issue.

**Comment by jonan** [comment]
The issue is known and fixed, but the version in Google Play hasn't been updated #736

**Comment by rogama25** [comment]
Then, how can I download it?

**Comment by jonan** [comment]
GitHub isn't doing official releases, so you'll have to compile it yourself or use [ForkHub](https://play.google.com/store/apps/details?id=jp.forkhub)
