### ISSUE TITLE
Hit Targets For Secondary Navigation Too Small

### ISSUE THREAD

**Issue by JakeWharton** [github/android#82]
Android design guidelines recommend 48dp square as a minimum. On the action bar, action items have a minimm width of 56dp by default. On larger devices (e.g., Nexus 7) the action bar becomes 56dp tall rather than 48dp which further exacerbates the thinness.

![](http://i.imgur.com/9Agxa.png)
![](http://i.imgur.com/HobkD.png)
![](http://i.imgur.com/UjWoE.png)

For comparison, here's the overflow menu on the Galaxy Nexus:

![](http://i.imgur.com/3HsLb.png)

**Comment by Meisolsson** [comment]
I think this was fixed when switching to toolbars and AppCompat?
