### ISSUE TITLE
Allow installation on SD card

### ISSUE THREAD

**Issue by mjtamlyn** [github/android#90]
App is currently locked to be installed in local storage. I'm no droid dev, but looks like this attribute is the one you want: http://developer.android.com/guide/topics/data/install-location.html

For those of us with older smaller hard drive phones this is a must-have.

**Comment by EzraBrooks** [comment]
@fadils Can this issue be closed? Citing the App Install Location guidelines from the Android Developer API Guides as @kevinsawicki did above, GitHub should not be out-of-the-box installable on external storage.

**Comment by fadils** [comment]
Thanks @EzraBrooks
