### ISSUE TITLE
A few things.

### ISSUE THREAD

**Issue by Southern** [github/android#99]
- Why does this app request access to manage device accounts, and administer the devices, when Github doesn't have features to control said access to its users?

- Needs to be able to logout.

- I currently have 3 issues that are mentioning me, and one opened by me. None show in the dashboard.

**Comment by EzraBrooks** [comment]
This issue now boils down to the idiosyncrasies within the app dealing with repository issues, which are mentioned in many other issues.

**Comment by fadils** [comment]
Moved to #312
